name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Lint, Typecheck and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install
        run: yarn --frozen-lockfile

      - name: Generate Prisma Client
        run: yarn prisma generate

      - name: Check Formatting
        run: yarn format:check

      - name: Lint and Type-check
        run: yarn check

      - name: Build Project
        run: yarn build
        env:
          NEXT_TELEMETRY_DISABLED: 1
